version: '3.9'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - weather_network

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn weather_project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=weather_project.settings
    networks:
      - weather_network

networks:
  weather_network:
    driver: bridge

volumes:
  postgres_data:
