# Generated by Django 5.2.1 on 2025-05-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='wind_speed',
        ),
    ]
