# Generated by Django 5.0.2 on 2025-05-27 01:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='city',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='last_search',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
